apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: xrpd-toolbox
  title: xrpd-toolbox
  description: A repository for useful python data analysis tools for the X-ray powder diffraction beamlines at Diamond Light Source
spec:
  type: library
  lifecycle: experimental
  owner: group:default/data-analysis
